[package]
name = "beneath-a-steel-sky-extract"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.10", default-features = false, features = ["derive", "error-context", "help", "std", "usage"] }
csv = "1.2.2"
serde = { version = "1.0.164", features = ["serde_derive"] }
